syntax = "proto3";
package admin;

import "google/protobuf/struct.proto";
import "google/protobuf/empty.proto";

service IAdminAuthService {
    rpc get_self (google.protobuf.Empty) returns (GetSelfResponse);
    rpc get_user (GetUserRequest) returns (GetUserResponse);
    rpc delete_user (DeleteUserRequest) returns (DeleteUserResponse);
}

message GetSelfResponse {
    google.protobuf.Struct return_value = 1;
}

message GetUserRequest {
    optional string user_id = 1;
    optional string username = 2;
}

message GetUserResponse {
    google.protobuf.Struct return_value = 1;
}

message DeleteUserRequest {
    optional string user_id = 1;
    optional string username = 2;
}

message DeleteUserResponse {
    google.protobuf.Struct return_value = 1;
}