"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetSelfResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSelfResponse: _TypeAlias = GetSelfResponse  # noqa: Y015

@_typing.final
class GetUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    username: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str | None = ...,
        username: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_user_id", b"_user_id", "_username", b"_username", "user_id", b"user_id", "username", b"username"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_user_id", b"_user_id", "_username", b"_username", "user_id", b"user_id", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__user_id: _TypeAlias = _typing.Literal["user_id"]  # noqa: Y015
    _WhichOneofArgType__user_id: _TypeAlias = _typing.Literal["_user_id", b"_user_id"]  # noqa: Y015
    _WhichOneofReturnType__username: _TypeAlias = _typing.Literal["username"]  # noqa: Y015
    _WhichOneofArgType__username: _TypeAlias = _typing.Literal["_username", b"_username"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__user_id) -> _WhichOneofReturnType__user_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__username) -> _WhichOneofReturnType__username | None: ...

Global___GetUserRequest: _TypeAlias = GetUserRequest  # noqa: Y015

@_typing.final
class GetUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserResponse: _TypeAlias = GetUserResponse  # noqa: Y015

@_typing.final
class DeleteUserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    username: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str | None = ...,
        username: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_user_id", b"_user_id", "_username", b"_username", "user_id", b"user_id", "username", b"username"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_user_id", b"_user_id", "_username", b"_username", "user_id", b"user_id", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__user_id: _TypeAlias = _typing.Literal["user_id"]  # noqa: Y015
    _WhichOneofArgType__user_id: _TypeAlias = _typing.Literal["_user_id", b"_user_id"]  # noqa: Y015
    _WhichOneofReturnType__username: _TypeAlias = _typing.Literal["username"]  # noqa: Y015
    _WhichOneofArgType__username: _TypeAlias = _typing.Literal["_username", b"_username"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__user_id) -> _WhichOneofReturnType__user_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__username) -> _WhichOneofReturnType__username | None: ...

Global___DeleteUserRequest: _TypeAlias = DeleteUserRequest  # noqa: Y015

@_typing.final
class DeleteUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteUserResponse: _TypeAlias = DeleteUserResponse  # noqa: Y015
