"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Role:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Role.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ADMIN: _Role.ValueType  # 0
    USER: _Role.ValueType  # 1

class Role(_Role, metaclass=_RoleEnumTypeWrapper): ...

ADMIN: Role.ValueType  # 0
USER: Role.ValueType  # 1
Global___Role: _TypeAlias = Role  # noqa: Y015

@_typing.final
class RegisterInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    email: _builtins.str
    username: _builtins.str
    password: _builtins.str
    role: Global___Role.ValueType
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        email: _builtins.str = ...,
        username: _builtins.str = ...,
        password: _builtins.str = ...,
        role: Global___Role.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["email", b"email", "name", b"name", "password", b"password", "role", b"role", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterInput: _TypeAlias = RegisterInput  # noqa: Y015

@_typing.final
class LoginInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    username: _builtins.str
    password: _builtins.str
    def __init__(
        self,
        *,
        username: _builtins.str = ...,
        password: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["password", b"password", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LoginInput: _TypeAlias = LoginInput  # noqa: Y015

@_typing.final
class RegisterResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterResponse: _TypeAlias = RegisterResponse  # noqa: Y015

@_typing.final
class LoginResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LoginResponse: _TypeAlias = LoginResponse  # noqa: Y015

@_typing.final
class RefreshTokenResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RefreshTokenResponse: _TypeAlias = RefreshTokenResponse  # noqa: Y015
