services:

  # Nginx
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - auth-service
      - product-service
      - order-service
      - admin-service
      - user-service
    ports:
      - ${EXTERNAL_FASTAPI_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  auth-service:
    working_dir: /app
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
      - postgres-db
    expose:
      - ${INTERNAL_FASTAPI_PORT}
    command: ["fastapi", "run", "./src/main.py", "--port", "${INTERNAL_FASTAPI_PORT}"]

  product-service:
    working_dir: /app
    build:
      context: ./product_service
      dockerfile: Dockerfile
    container_name: product_service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
      - postgres-db
    expose:
      - ${INTERNAL_FASTAPI_PORT}
    command: ["fastapi", "run", "./src/main.py", "--port", "${INTERNAL_FASTAPI_PORT}"]

  order-service:
    working_dir: /app
    build:
      context: ./order_service
      dockerfile: Dockerfile
    container_name: order_service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
      - postgres-db
    expose:
      - ${INTERNAL_FASTAPI_PORT}
    command: ["fastapi", "run", "./src/main.py", "--port", "${INTERNAL_FASTAPI_PORT}"]

  admin-service:
    working_dir: /app
    build:
      context: ./admin_service
      dockerfile: Dockerfile
    container_name: admin_service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
      - postgres-db
    expose:
      - ${INTERNAL_FASTAPI_PORT}
    command: ["fastapi", "run", "./src/main.py", "--port", "${INTERNAL_FASTAPI_PORT}"]

  user-service:
    working_dir: /app
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
      - postgres-db
    expose:
      - ${INTERNAL_FASTAPI_PORT}
    command: ["fastapi", "run", "./src/main.py", "--port", "${INTERNAL_FASTAPI_PORT}"]

  # Mongo-db
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

  # Postgresql
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    expose:
      - 5432
    ports:
      - 54032:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - postgres-db

volumes:
  pgdata:
  mongo_data:
