# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import src.worker.grpc_worker.service.admin_order_service_pb2 as admin__order__service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in admin_order_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IAdminOrderServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_by_id = channel.unary_unary(
                '/admin_order.IAdminOrderService/get_by_id',
                request_serializer=admin__order__service__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=admin__order__service__pb2.GetByIdResponse.FromString,
                _registered_method=True)
        self.modify = channel.unary_unary(
                '/admin_order.IAdminOrderService/modify',
                request_serializer=admin__order__service__pb2.ModifyOrderInput.SerializeToString,
                response_deserializer=admin__order__service__pb2.ModifyResponse.FromString,
                _registered_method=True)
        self.delete_by_id = channel.unary_unary(
                '/admin_order.IAdminOrderService/delete_by_id',
                request_serializer=admin__order__service__pb2.DeleteByIdRequest.SerializeToString,
                response_deserializer=admin__order__service__pb2.DeleteByIdResponse.FromString,
                _registered_method=True)
        self.get_by_criteria = channel.unary_unary(
                '/admin_order.IAdminOrderService/get_by_criteria',
                request_serializer=admin__order__service__pb2.OrderFilterInput.SerializeToString,
                response_deserializer=admin__order__service__pb2.GetByCriteriaResponse.FromString,
                _registered_method=True)
        self.delete_by_criteria = channel.unary_unary(
                '/admin_order.IAdminOrderService/delete_by_criteria',
                request_serializer=admin__order__service__pb2.OrderFilterInput.SerializeToString,
                response_deserializer=admin__order__service__pb2.DeleteByCriteriaResponse.FromString,
                _registered_method=True)


class IAdminOrderServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def get_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def modify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_by_criteria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_by_criteria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IAdminOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_by_id,
                    request_deserializer=admin__order__service__pb2.GetByIdRequest.FromString,
                    response_serializer=admin__order__service__pb2.GetByIdResponse.SerializeToString,
            ),
            'modify': grpc.unary_unary_rpc_method_handler(
                    servicer.modify,
                    request_deserializer=admin__order__service__pb2.ModifyOrderInput.FromString,
                    response_serializer=admin__order__service__pb2.ModifyResponse.SerializeToString,
            ),
            'delete_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_by_id,
                    request_deserializer=admin__order__service__pb2.DeleteByIdRequest.FromString,
                    response_serializer=admin__order__service__pb2.DeleteByIdResponse.SerializeToString,
            ),
            'get_by_criteria': grpc.unary_unary_rpc_method_handler(
                    servicer.get_by_criteria,
                    request_deserializer=admin__order__service__pb2.OrderFilterInput.FromString,
                    response_serializer=admin__order__service__pb2.GetByCriteriaResponse.SerializeToString,
            ),
            'delete_by_criteria': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_by_criteria,
                    request_deserializer=admin__order__service__pb2.OrderFilterInput.FromString,
                    response_serializer=admin__order__service__pb2.DeleteByCriteriaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin_order.IAdminOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin_order.IAdminOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IAdminOrderService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin_order.IAdminOrderService/get_by_id',
            admin__order__service__pb2.GetByIdRequest.SerializeToString,
            admin__order__service__pb2.GetByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def modify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin_order.IAdminOrderService/modify',
            admin__order__service__pb2.ModifyOrderInput.SerializeToString,
            admin__order__service__pb2.ModifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin_order.IAdminOrderService/delete_by_id',
            admin__order__service__pb2.DeleteByIdRequest.SerializeToString,
            admin__order__service__pb2.DeleteByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_by_criteria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin_order.IAdminOrderService/get_by_criteria',
            admin__order__service__pb2.OrderFilterInput.SerializeToString,
            admin__order__service__pb2.GetByCriteriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_by_criteria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin_order.IAdminOrderService/delete_by_criteria',
            admin__order__service__pb2.OrderFilterInput.SerializeToString,
            admin__order__service__pb2.DeleteByCriteriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
