"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class OrderFilterInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    START_QUANTITY_FIELD_NUMBER: _builtins.int
    END_QUANTITY_FIELD_NUMBER: _builtins.int
    START_DATE_FIELD_NUMBER: _builtins.int
    END_DATE_FIELD_NUMBER: _builtins.int
    start_quantity: _builtins.int
    end_quantity: _builtins.int
    @_builtins.property
    def user_id(self) -> _struct_pb2.Value: ...
    @_builtins.property
    def product_id(self) -> _struct_pb2.Value: ...
    @_builtins.property
    def status(self) -> _struct_pb2.ListValue: ...
    @_builtins.property
    def start_date(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def end_date(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        user_id: _struct_pb2.Value | None = ...,
        product_id: _struct_pb2.Value | None = ...,
        status: _struct_pb2.ListValue | None = ...,
        start_quantity: _builtins.int | None = ...,
        end_quantity: _builtins.int | None = ...,
        start_date: _timestamp_pb2.Timestamp | None = ...,
        end_date: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_end_date", b"_end_date", "_end_quantity", b"_end_quantity", "_product_id", b"_product_id", "_start_date", b"_start_date", "_start_quantity", b"_start_quantity", "_status", b"_status", "_user_id", b"_user_id", "end_date", b"end_date", "end_quantity", b"end_quantity", "product_id", b"product_id", "start_date", b"start_date", "start_quantity", b"start_quantity", "status", b"status", "user_id", b"user_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_end_date", b"_end_date", "_end_quantity", b"_end_quantity", "_product_id", b"_product_id", "_start_date", b"_start_date", "_start_quantity", b"_start_quantity", "_status", b"_status", "_user_id", b"_user_id", "end_date", b"end_date", "end_quantity", b"end_quantity", "product_id", b"product_id", "start_date", b"start_date", "start_quantity", b"start_quantity", "status", b"status", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__end_date: _TypeAlias = _typing.Literal["end_date"]  # noqa: Y015
    _WhichOneofArgType__end_date: _TypeAlias = _typing.Literal["_end_date", b"_end_date"]  # noqa: Y015
    _WhichOneofReturnType__end_quantity: _TypeAlias = _typing.Literal["end_quantity"]  # noqa: Y015
    _WhichOneofArgType__end_quantity: _TypeAlias = _typing.Literal["_end_quantity", b"_end_quantity"]  # noqa: Y015
    _WhichOneofReturnType__product_id: _TypeAlias = _typing.Literal["product_id"]  # noqa: Y015
    _WhichOneofArgType__product_id: _TypeAlias = _typing.Literal["_product_id", b"_product_id"]  # noqa: Y015
    _WhichOneofReturnType__start_date: _TypeAlias = _typing.Literal["start_date"]  # noqa: Y015
    _WhichOneofArgType__start_date: _TypeAlias = _typing.Literal["_start_date", b"_start_date"]  # noqa: Y015
    _WhichOneofReturnType__start_quantity: _TypeAlias = _typing.Literal["start_quantity"]  # noqa: Y015
    _WhichOneofArgType__start_quantity: _TypeAlias = _typing.Literal["_start_quantity", b"_start_quantity"]  # noqa: Y015
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    _WhichOneofReturnType__user_id: _TypeAlias = _typing.Literal["user_id"]  # noqa: Y015
    _WhichOneofArgType__user_id: _TypeAlias = _typing.Literal["_user_id", b"_user_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_date) -> _WhichOneofReturnType__end_date | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_quantity) -> _WhichOneofReturnType__end_quantity | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__product_id) -> _WhichOneofReturnType__product_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_date) -> _WhichOneofReturnType__start_date | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_quantity) -> _WhichOneofReturnType__start_quantity | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__user_id) -> _WhichOneofReturnType__user_id | None: ...

Global___OrderFilterInput: _TypeAlias = OrderFilterInput  # noqa: Y015

@_typing.final
class PlaceOrderInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    QUANTITY_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    quantity: _builtins.int
    description: _builtins.str
    @_builtins.property
    def product_id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        product_id: _struct_pb2.Value | None = ...,
        quantity: _builtins.int | None = ...,
        description: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_quantity", b"_quantity", "description", b"description", "product_id", b"product_id", "quantity", b"quantity"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_quantity", b"_quantity", "description", b"description", "product_id", b"product_id", "quantity", b"quantity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    _WhichOneofReturnType__quantity: _TypeAlias = _typing.Literal["quantity"]  # noqa: Y015
    _WhichOneofArgType__quantity: _TypeAlias = _typing.Literal["_quantity", b"_quantity"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__quantity) -> _WhichOneofReturnType__quantity | None: ...

Global___PlaceOrderInput: _TypeAlias = PlaceOrderInput  # noqa: Y015

@_typing.final
class UpdateOrderInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    description: _builtins.str
    @_builtins.property
    def id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        id: _struct_pb2.Value | None = ...,
        description: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description", "id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "description", b"description", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...

Global___UpdateOrderInput: _TypeAlias = UpdateOrderInput  # noqa: Y015

@_typing.final
class PlaceOrderResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlaceOrderResponse: _TypeAlias = PlaceOrderResponse  # noqa: Y015

@_typing.final
class GetByIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByIdRequest: _TypeAlias = GetByIdRequest  # noqa: Y015

@_typing.final
class GetByIdResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByIdResponse: _TypeAlias = GetByIdResponse  # noqa: Y015

@_typing.final
class UpdateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateResponse: _TypeAlias = UpdateResponse  # noqa: Y015

@_typing.final
class GetByCriteriaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.ListValue: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.ListValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByCriteriaResponse: _TypeAlias = GetByCriteriaResponse  # noqa: Y015
