# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'product_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15product_service.proto\x12\x07product\x1a\x1cgoogle/protobuf/struct.proto\"$\n\x0eGetByIdRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"@\n\x0fGetByIdResponse\x12-\n\x0creturn_value\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2Q\n\x0fIProductService\x12>\n\tget_by_id\x12\x17.product.GetByIdRequest\x1a\x18.product.GetByIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBYIDREQUEST']._serialized_start=64
  _globals['_GETBYIDREQUEST']._serialized_end=100
  _globals['_GETBYIDRESPONSE']._serialized_start=102
  _globals['_GETBYIDRESPONSE']._serialized_end=166
  _globals['_IPRODUCTSERVICE']._serialized_start=168
  _globals['_IPRODUCTSERVICE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
