apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: mhdlt/order:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config


apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
