apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: registry-fc6690c55a-mini-ecommerce.apps.ir-central1.arvancaas.ir/admin/user:latest
          imagePullSecrets:
            - name: arvan-regcred
          ports:
            - containerPort: 8000
          # envFrom:
          #   - configMapRef:
          #       name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
