# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\x04\x61uth\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"j\n\rRegisterInput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x18\n\x04role\x18\x05 \x01(\x0e\x32\n.auth.Role\"0\n\nLoginInput\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"A\n\x10RegisterResponse\x12-\n\x0creturn_value\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\">\n\rLoginResponse\x12-\n\x0creturn_value\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"E\n\x14RefreshTokenResponse\x12-\n\x0creturn_value\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct*\x1b\n\x04Role\x12\t\n\x05\x41\x44MIN\x10\x00\x12\x08\n\x04USER\x10\x01\x32\xbc\x01\n\x0cIAuthService\x12\x37\n\x08register\x12\x13.auth.RegisterInput\x1a\x16.auth.RegisterResponse\x12.\n\x05login\x12\x10.auth.LoginInput\x1a\x13.auth.LoginResponse\x12\x43\n\rrefresh_token\x12\x16.google.protobuf.Empty\x1a\x1a.auth.RefreshTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=447
  _globals['_ROLE']._serialized_end=474
  _globals['_REGISTERINPUT']._serialized_start=87
  _globals['_REGISTERINPUT']._serialized_end=193
  _globals['_LOGININPUT']._serialized_start=195
  _globals['_LOGININPUT']._serialized_end=243
  _globals['_REGISTERRESPONSE']._serialized_start=245
  _globals['_REGISTERRESPONSE']._serialized_end=310
  _globals['_LOGINRESPONSE']._serialized_start=312
  _globals['_LOGINRESPONSE']._serialized_end=374
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=376
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=445
  _globals['_IAUTHSERVICE']._serialized_start=477
  _globals['_IAUTHSERVICE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
