# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'product_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15product_service.proto\x12\x07product\x1a\x1cgoogle/protobuf/struct.proto\"\xa6\x01\n\x12ProductFilterInput\x12\x30\n\x0b\x63\x61tegory_id\x18\x01 \x01(\x0b\x32\x16.google.protobuf.ValueH\x00\x88\x01\x01\x12\x18\n\x0bstart_price\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x16\n\tend_price\x18\x03 \x01(\x02H\x02\x88\x01\x01\x42\x0e\n\x0c_category_idB\x0e\n\x0c_start_priceB\x0c\n\n_end_price\"$\n\x0eGetByIdRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"@\n\x0fGetByIdResponse\x12-\n\x0creturn_value\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"I\n\x15GetByCriteriaResponse\x12\x30\n\x0creturn_value\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.ListValue2\xa1\x01\n\x0fIProductService\x12>\n\tget_by_id\x12\x17.product.GetByIdRequest\x1a\x18.product.GetByIdResponse\x12N\n\x0fget_by_criteria\x12\x1b.product.ProductFilterInput\x1a\x1e.product.GetByCriteriaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTFILTERINPUT']._serialized_start=65
  _globals['_PRODUCTFILTERINPUT']._serialized_end=231
  _globals['_GETBYIDREQUEST']._serialized_start=233
  _globals['_GETBYIDREQUEST']._serialized_end=269
  _globals['_GETBYIDRESPONSE']._serialized_start=271
  _globals['_GETBYIDRESPONSE']._serialized_end=335
  _globals['_GETBYCRITERIARESPONSE']._serialized_start=337
  _globals['_GETBYCRITERIARESPONSE']._serialized_end=410
  _globals['_IPRODUCTSERVICE']._serialized_start=413
  _globals['_IPRODUCTSERVICE']._serialized_end=574
# @@protoc_insertion_point(module_scope)
