"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ProductFilterInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CATEGORY_ID_FIELD_NUMBER: _builtins.int
    START_PRICE_FIELD_NUMBER: _builtins.int
    END_PRICE_FIELD_NUMBER: _builtins.int
    start_price: _builtins.float
    end_price: _builtins.float
    @_builtins.property
    def category_id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        category_id: _struct_pb2.Value | None = ...,
        start_price: _builtins.float | None = ...,
        end_price: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_category_id", b"_category_id", "_end_price", b"_end_price", "_start_price", b"_start_price", "category_id", b"category_id", "end_price", b"end_price", "start_price", b"start_price"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_category_id", b"_category_id", "_end_price", b"_end_price", "_start_price", b"_start_price", "category_id", b"category_id", "end_price", b"end_price", "start_price", b"start_price"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__category_id: _TypeAlias = _typing.Literal["category_id"]  # noqa: Y015
    _WhichOneofArgType__category_id: _TypeAlias = _typing.Literal["_category_id", b"_category_id"]  # noqa: Y015
    _WhichOneofReturnType__end_price: _TypeAlias = _typing.Literal["end_price"]  # noqa: Y015
    _WhichOneofArgType__end_price: _TypeAlias = _typing.Literal["_end_price", b"_end_price"]  # noqa: Y015
    _WhichOneofReturnType__start_price: _TypeAlias = _typing.Literal["start_price"]  # noqa: Y015
    _WhichOneofArgType__start_price: _TypeAlias = _typing.Literal["_start_price", b"_start_price"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__category_id) -> _WhichOneofReturnType__category_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_price) -> _WhichOneofReturnType__end_price | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_price) -> _WhichOneofReturnType__start_price | None: ...

Global___ProductFilterInput: _TypeAlias = ProductFilterInput  # noqa: Y015

@_typing.final
class GetByIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    product_id: _builtins.str
    def __init__(
        self,
        *,
        product_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product_id", b"product_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByIdRequest: _TypeAlias = GetByIdRequest  # noqa: Y015

@_typing.final
class GetByIdResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByIdResponse: _TypeAlias = GetByIdResponse  # noqa: Y015

@_typing.final
class GetByCriteriaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.ListValue: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.ListValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByCriteriaResponse: _TypeAlias = GetByCriteriaResponse  # noqa: Y015
