"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateCategoryInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARENT_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    slug: _builtins.str
    @_builtins.property
    def parent_id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        parent_id: _struct_pb2.Value | None = ...,
        name: _builtins.str = ...,
        slug: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_parent_id", b"_parent_id", "parent_id", b"parent_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_parent_id", b"_parent_id", "name", b"name", "parent_id", b"parent_id", "slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__parent_id: _TypeAlias = _typing.Literal["parent_id"]  # noqa: Y015
    _WhichOneofArgType__parent_id: _TypeAlias = _typing.Literal["_parent_id", b"_parent_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parent_id) -> _WhichOneofReturnType__parent_id | None: ...

Global___CreateCategoryInput: _TypeAlias = CreateCategoryInput  # noqa: Y015

@_typing.final
class UpdateCategoryInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    PARENT_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    SLUG_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    slug: _builtins.str
    @_builtins.property
    def id(self) -> _struct_pb2.Value: ...
    @_builtins.property
    def parent_id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        id: _struct_pb2.Value | None = ...,
        parent_id: _struct_pb2.Value | None = ...,
        name: _builtins.str | None = ...,
        slug: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "_parent_id", b"_parent_id", "_slug", b"_slug", "id", b"id", "name", b"name", "parent_id", b"parent_id", "slug", b"slug"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "_parent_id", b"_parent_id", "_slug", b"_slug", "id", b"id", "name", b"name", "parent_id", b"parent_id", "slug", b"slug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    _WhichOneofReturnType__parent_id: _TypeAlias = _typing.Literal["parent_id"]  # noqa: Y015
    _WhichOneofArgType__parent_id: _TypeAlias = _typing.Literal["_parent_id", b"_parent_id"]  # noqa: Y015
    _WhichOneofReturnType__slug: _TypeAlias = _typing.Literal["slug"]  # noqa: Y015
    _WhichOneofArgType__slug: _TypeAlias = _typing.Literal["_slug", b"_slug"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__parent_id) -> _WhichOneofReturnType__parent_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__slug) -> _WhichOneofReturnType__slug | None: ...

Global___UpdateCategoryInput: _TypeAlias = UpdateCategoryInput  # noqa: Y015

@_typing.final
class CategoryFilterInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    BASED_ON_FIELD_NUMBER: _builtins.int
    CONTAINS_DANGLINGS_FIELD_NUMBER: _builtins.int
    based_on: _builtins.str
    contains_danglings: _builtins.bool
    @_builtins.property
    def id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        id: _struct_pb2.Value | None = ...,
        based_on: _builtins.str = ...,
        contains_danglings: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_id", b"_id", "id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_id", b"_id", "based_on", b"based_on", "contains_danglings", b"contains_danglings", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__id: _TypeAlias = _typing.Literal["id"]  # noqa: Y015
    _WhichOneofArgType__id: _TypeAlias = _typing.Literal["_id", b"_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__id) -> _WhichOneofReturnType__id | None: ...

Global___CategoryFilterInput: _TypeAlias = CategoryFilterInput  # noqa: Y015

@_typing.final
class CreateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateResponse: _TypeAlias = CreateResponse  # noqa: Y015

@_typing.final
class GetByIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CATEGORY_ID_FIELD_NUMBER: _builtins.int
    category_id: _builtins.str
    def __init__(
        self,
        *,
        category_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["category_id", b"category_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByIdRequest: _TypeAlias = GetByIdRequest  # noqa: Y015

@_typing.final
class GetByIdResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByIdResponse: _TypeAlias = GetByIdResponse  # noqa: Y015

@_typing.final
class UpdateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateResponse: _TypeAlias = UpdateResponse  # noqa: Y015

@_typing.final
class DeleteByIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CATEGORY_ID_FIELD_NUMBER: _builtins.int
    category_id: _builtins.str
    def __init__(
        self,
        *,
        category_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["category_id", b"category_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteByIdRequest: _TypeAlias = DeleteByIdRequest  # noqa: Y015

@_typing.final
class DeleteByIdResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteByIdResponse: _TypeAlias = DeleteByIdResponse  # noqa: Y015

@_typing.final
class GetByCriteriaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.ListValue: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.ListValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByCriteriaResponse: _TypeAlias = GetByCriteriaResponse  # noqa: Y015

@_typing.final
class DeleteAllResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteAllResponse: _TypeAlias = DeleteAllResponse  # noqa: Y015
