# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import src.worker.grpc_worker.service.product_service_pb2 as product__service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IProductServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create = channel.unary_unary(
                '/product.IProductService/create',
                request_serializer=product__service__pb2.CreateProductInput.SerializeToString,
                response_deserializer=product__service__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.get_by_id = channel.unary_unary(
                '/product.IProductService/get_by_id',
                request_serializer=product__service__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=product__service__pb2.GetByIdResponse.FromString,
                _registered_method=True)
        self.update = channel.unary_unary(
                '/product.IProductService/update',
                request_serializer=product__service__pb2.UpdateProductInput.SerializeToString,
                response_deserializer=product__service__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.delete_by_id = channel.unary_unary(
                '/product.IProductService/delete_by_id',
                request_serializer=product__service__pb2.DeleteByIdRequest.SerializeToString,
                response_deserializer=product__service__pb2.DeleteByIdResponse.FromString,
                _registered_method=True)
        self.get_by_criteria = channel.unary_unary(
                '/product.IProductService/get_by_criteria',
                request_serializer=product__service__pb2.ProductFilterInput.SerializeToString,
                response_deserializer=product__service__pb2.GetByCriteriaResponse.FromString,
                _registered_method=True)
        self.delete_all = channel.unary_unary(
                '/product.IProductService/delete_all',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=product__service__pb2.DeleteAllResponse.FromString,
                _registered_method=True)


class IProductServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_by_criteria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_all(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=product__service__pb2.CreateProductInput.FromString,
                    response_serializer=product__service__pb2.CreateResponse.SerializeToString,
            ),
            'get_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_by_id,
                    request_deserializer=product__service__pb2.GetByIdRequest.FromString,
                    response_serializer=product__service__pb2.GetByIdResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=product__service__pb2.UpdateProductInput.FromString,
                    response_serializer=product__service__pb2.UpdateResponse.SerializeToString,
            ),
            'delete_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_by_id,
                    request_deserializer=product__service__pb2.DeleteByIdRequest.FromString,
                    response_serializer=product__service__pb2.DeleteByIdResponse.SerializeToString,
            ),
            'get_by_criteria': grpc.unary_unary_rpc_method_handler(
                    servicer.get_by_criteria,
                    request_deserializer=product__service__pb2.ProductFilterInput.FromString,
                    response_serializer=product__service__pb2.GetByCriteriaResponse.SerializeToString,
            ),
            'delete_all': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_all,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=product__service__pb2.DeleteAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.IProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.IProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IProductService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.IProductService/create',
            product__service__pb2.CreateProductInput.SerializeToString,
            product__service__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.IProductService/get_by_id',
            product__service__pb2.GetByIdRequest.SerializeToString,
            product__service__pb2.GetByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.IProductService/update',
            product__service__pb2.UpdateProductInput.SerializeToString,
            product__service__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.IProductService/delete_by_id',
            product__service__pb2.DeleteByIdRequest.SerializeToString,
            product__service__pb2.DeleteByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_by_criteria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.IProductService/get_by_criteria',
            product__service__pb2.ProductFilterInput.SerializeToString,
            product__service__pb2.GetByCriteriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_all(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.IProductService/delete_all',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            product__service__pb2.DeleteAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
