"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateProductInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CATEGORY_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    STOCK_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    description: _builtins.str
    price: _builtins.float
    stock: _builtins.float
    @_builtins.property
    def category_id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        category_id: _struct_pb2.Value | None = ...,
        name: _builtins.str = ...,
        description: _builtins.str | None = ...,
        price: _builtins.float | None = ...,
        stock: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_price", b"_price", "_stock", b"_stock", "category_id", b"category_id", "description", b"description", "price", b"price", "stock", b"stock"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_description", b"_description", "_price", b"_price", "_stock", b"_stock", "category_id", b"category_id", "description", b"description", "name", b"name", "price", b"price", "stock", b"stock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    _WhichOneofReturnType__price: _TypeAlias = _typing.Literal["price"]  # noqa: Y015
    _WhichOneofArgType__price: _TypeAlias = _typing.Literal["_price", b"_price"]  # noqa: Y015
    _WhichOneofReturnType__stock: _TypeAlias = _typing.Literal["stock"]  # noqa: Y015
    _WhichOneofArgType__stock: _TypeAlias = _typing.Literal["_stock", b"_stock"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__price) -> _WhichOneofReturnType__price | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__stock) -> _WhichOneofReturnType__stock | None: ...

Global___CreateProductInput: _TypeAlias = CreateProductInput  # noqa: Y015

@_typing.final
class UpdateProductInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    CATEGORY_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    STOCK_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    description: _builtins.str
    price: _builtins.float
    stock: _builtins.float
    @_builtins.property
    def id(self) -> _struct_pb2.Value: ...
    @_builtins.property
    def category_id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        id: _struct_pb2.Value | None = ...,
        category_id: _struct_pb2.Value | None = ...,
        name: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        price: _builtins.float | None = ...,
        stock: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_category_id", b"_category_id", "_description", b"_description", "_name", b"_name", "_price", b"_price", "_stock", b"_stock", "category_id", b"category_id", "description", b"description", "id", b"id", "name", b"name", "price", b"price", "stock", b"stock"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_category_id", b"_category_id", "_description", b"_description", "_name", b"_name", "_price", b"_price", "_stock", b"_stock", "category_id", b"category_id", "description", b"description", "id", b"id", "name", b"name", "price", b"price", "stock", b"stock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__category_id: _TypeAlias = _typing.Literal["category_id"]  # noqa: Y015
    _WhichOneofArgType__category_id: _TypeAlias = _typing.Literal["_category_id", b"_category_id"]  # noqa: Y015
    _WhichOneofReturnType__description: _TypeAlias = _typing.Literal["description"]  # noqa: Y015
    _WhichOneofArgType__description: _TypeAlias = _typing.Literal["_description", b"_description"]  # noqa: Y015
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    _WhichOneofReturnType__price: _TypeAlias = _typing.Literal["price"]  # noqa: Y015
    _WhichOneofArgType__price: _TypeAlias = _typing.Literal["_price", b"_price"]  # noqa: Y015
    _WhichOneofReturnType__stock: _TypeAlias = _typing.Literal["stock"]  # noqa: Y015
    _WhichOneofArgType__stock: _TypeAlias = _typing.Literal["_stock", b"_stock"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__category_id) -> _WhichOneofReturnType__category_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__description) -> _WhichOneofReturnType__description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__price) -> _WhichOneofReturnType__price | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__stock) -> _WhichOneofReturnType__stock | None: ...

Global___UpdateProductInput: _TypeAlias = UpdateProductInput  # noqa: Y015

@_typing.final
class ProductFilterInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CATEGORY_ID_FIELD_NUMBER: _builtins.int
    START_PRICE_FIELD_NUMBER: _builtins.int
    END_PRICE_FIELD_NUMBER: _builtins.int
    start_price: _builtins.float
    end_price: _builtins.float
    @_builtins.property
    def category_id(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        category_id: _struct_pb2.Value | None = ...,
        start_price: _builtins.float | None = ...,
        end_price: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_category_id", b"_category_id", "_end_price", b"_end_price", "_start_price", b"_start_price", "category_id", b"category_id", "end_price", b"end_price", "start_price", b"start_price"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_category_id", b"_category_id", "_end_price", b"_end_price", "_start_price", b"_start_price", "category_id", b"category_id", "end_price", b"end_price", "start_price", b"start_price"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__category_id: _TypeAlias = _typing.Literal["category_id"]  # noqa: Y015
    _WhichOneofArgType__category_id: _TypeAlias = _typing.Literal["_category_id", b"_category_id"]  # noqa: Y015
    _WhichOneofReturnType__end_price: _TypeAlias = _typing.Literal["end_price"]  # noqa: Y015
    _WhichOneofArgType__end_price: _TypeAlias = _typing.Literal["_end_price", b"_end_price"]  # noqa: Y015
    _WhichOneofReturnType__start_price: _TypeAlias = _typing.Literal["start_price"]  # noqa: Y015
    _WhichOneofArgType__start_price: _TypeAlias = _typing.Literal["_start_price", b"_start_price"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__category_id) -> _WhichOneofReturnType__category_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_price) -> _WhichOneofReturnType__end_price | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_price) -> _WhichOneofReturnType__start_price | None: ...

Global___ProductFilterInput: _TypeAlias = ProductFilterInput  # noqa: Y015

@_typing.final
class CreateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateResponse: _TypeAlias = CreateResponse  # noqa: Y015

@_typing.final
class GetByIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    product_id: _builtins.str
    def __init__(
        self,
        *,
        product_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product_id", b"product_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByIdRequest: _TypeAlias = GetByIdRequest  # noqa: Y015

@_typing.final
class GetByIdResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByIdResponse: _TypeAlias = GetByIdResponse  # noqa: Y015

@_typing.final
class UpdateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateResponse: _TypeAlias = UpdateResponse  # noqa: Y015

@_typing.final
class DeleteByIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    product_id: _builtins.str
    def __init__(
        self,
        *,
        product_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product_id", b"product_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteByIdRequest: _TypeAlias = DeleteByIdRequest  # noqa: Y015

@_typing.final
class DeleteByIdResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteByIdResponse: _TypeAlias = DeleteByIdResponse  # noqa: Y015

@_typing.final
class GetByCriteriaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.ListValue: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.ListValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetByCriteriaResponse: _TypeAlias = GetByCriteriaResponse  # noqa: Y015

@_typing.final
class DeleteAllResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def return_value(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        return_value: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["return_value", b"return_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteAllResponse: _TypeAlias = DeleteAllResponse  # noqa: Y015
