# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_order_service_pb2 as user__order__service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_order_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IOrderServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.place_order = channel.unary_unary(
                '/user_order.IOrderService/place_order',
                request_serializer=user__order__service__pb2.PlaceOrderInput.SerializeToString,
                response_deserializer=user__order__service__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.get_by_id = channel.unary_unary(
                '/user_order.IOrderService/get_by_id',
                request_serializer=user__order__service__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=user__order__service__pb2.GetByIdResponse.FromString,
                _registered_method=True)
        self.update = channel.unary_unary(
                '/user_order.IOrderService/update',
                request_serializer=user__order__service__pb2.UpdateOrderInput.SerializeToString,
                response_deserializer=user__order__service__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.get_by_criteria = channel.unary_unary(
                '/user_order.IOrderService/get_by_criteria',
                request_serializer=user__order__service__pb2.OrderFilterInput.SerializeToString,
                response_deserializer=user__order__service__pb2.GetByCriteriaResponse.FromString,
                _registered_method=True)


class IOrderServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def place_order(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_by_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_by_criteria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'place_order': grpc.unary_unary_rpc_method_handler(
                    servicer.place_order,
                    request_deserializer=user__order__service__pb2.PlaceOrderInput.FromString,
                    response_serializer=user__order__service__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'get_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_by_id,
                    request_deserializer=user__order__service__pb2.GetByIdRequest.FromString,
                    response_serializer=user__order__service__pb2.GetByIdResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=user__order__service__pb2.UpdateOrderInput.FromString,
                    response_serializer=user__order__service__pb2.UpdateResponse.SerializeToString,
            ),
            'get_by_criteria': grpc.unary_unary_rpc_method_handler(
                    servicer.get_by_criteria,
                    request_deserializer=user__order__service__pb2.OrderFilterInput.FromString,
                    response_serializer=user__order__service__pb2.GetByCriteriaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user_order.IOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user_order.IOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IOrderService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def place_order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_order.IOrderService/place_order',
            user__order__service__pb2.PlaceOrderInput.SerializeToString,
            user__order__service__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_order.IOrderService/get_by_id',
            user__order__service__pb2.GetByIdRequest.SerializeToString,
            user__order__service__pb2.GetByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_order.IOrderService/update',
            user__order__service__pb2.UpdateOrderInput.SerializeToString,
            user__order__service__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_by_criteria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_order.IOrderService/get_by_criteria',
            user__order__service__pb2.OrderFilterInput.SerializeToString,
            user__order__service__pb2.GetByCriteriaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
