syntax = "proto3";
package user_order;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

service IOrderService {
    rpc place_order (PlaceOrderInput) returns (PlaceOrderResponse);
    rpc get_by_id (GetByIdRequest) returns (GetByIdResponse);
    rpc update (UpdateOrderInput) returns (UpdateResponse);
    rpc get_by_criteria (OrderFilterInput) returns (GetByCriteriaResponse);
}

message OrderFilterInput {
    optional google.protobuf.Value user_id = 1;
    optional google.protobuf.Value product_id = 2;
    optional google.protobuf.ListValue status = 3;
    optional int32 start_quantity = 4;
    optional int32 end_quantity = 5;
    optional google.protobuf.Timestamp start_date = 6;
    optional google.protobuf.Timestamp end_date = 7;
}

message PlaceOrderInput {
    google.protobuf.Value product_id = 1;
    optional int32 quantity = 2;
    optional string description = 3;
}

message UpdateOrderInput {
    google.protobuf.Value id = 1;
    optional string description = 2;
}

message PlaceOrderResponse {
    google.protobuf.Struct return_value = 1;
}

message GetByIdRequest {
    string order_id = 1;
}

message GetByIdResponse {
    google.protobuf.Struct return_value = 1;
}

message UpdateResponse {
    google.protobuf.Struct return_value = 1;
}

message GetByCriteriaResponse {
    google.protobuf.ListValue return_value = 1;
}