name: CI/CD with Kind

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # FastAPI Ports
      EXTERNAL_FASTAPI_PORT: ${{ vars.EXTERNAL_FASTAPI_PORT }}
      INTERNAL_FASTAPI_PORT: ${{ vars.INTERNAL_FASTAPI_PORT }}

      # Base URLs
      AUTH_BASE_URL: ${{ vars.AUTH_BASE_URL }}
      PRODUCT_BASE_URL: ${{ vars.PRODUCT_BASE_URL }}
      ORDER_BASE_URL: ${{ vars.ORDER_BASE_URL }}

      # DB Stack
      AUTH_DB_STACK: ${{ vars.AUTH_DB_STACK }}
      PRODUCT_DB_STACK: ${{ vars.PRODUCT_DB_STACK }}
      ORDER_DB_STACK: ${{ vars.ORDER_DB_STACK }}

      # MongoDB
      MONGO_HOST: ${{ vars.MONGO_HOST }}
      MONGO_PORT: ${{ vars.MONGO_PORT }}
      MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ vars.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_INITDB_DATABASE: ${{ vars.MONGO_INITDB_DATABASE }}

      # PostgreSQL
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}

      # PGAdmin
      PGADMIN_DEFAULT_EMAIL: ${{ vars.PGADMIN_DEFAULT_EMAIL }}
      PGADMIN_DEFAULT_PASSWORD: ${{ vars.PGADMIN_DEFAULT_PASSWORD }}

      # JWT
      JWT_SECRET: ${{ vars.JWT_SECRET }}
      JWT_ALGORITHM: ${{ vars.JWT_ALGORITHM }}
      JWT_EXPIRATION_MINUTES: ${{ vars.JWT_EXPIRATION_MINUTES }}
      JWT_REFRESH_EXPIRATION_MINUTES: ${{ vars.JWT_REFRESH_EXPIRATION_MINUTES }}

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Install Kind
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # 4. Create Kind cluster
      - name: Create Kind cluster
        run: |
          kind create cluster --name ci-cd-cluster

      # 5. Verify cluster
      - name: Check cluster nodes
        run: kubectl get nodes

      # 6. Build and load Docker images for FastAPI services
      - name: Build and load auth
        run: |
          docker build -t auth:latest ./auth_service
          kind load docker-image auth:latest --name ci-cd-cluster

      - name: Build and load product
        run: |
          docker build -t product:latest ./product_service
          kind load docker-image product:latest --name ci-cd-cluster

      - name: Build and load order
        run: |
          docker build -t order:latest ./order_service
          kind load docker-image order:latest --name ci-cd-cluster

      - name: Build and load admin
        run: |
          docker build -t admin:latest ./admin_service
          kind load docker-image admin:latest --name ci-cd-cluster

      - name: Build and load user
        run: |
          docker build -t user:latest ./user_service
          kind load docker-image user:latest --name ci-cd-cluster

      - name: Apply nginx ConfigMap from file
        run: |
          kubectl create configmap nginx-config --from-file=nginx.conf -o yaml --dry-run=client | kubectl apply -f -

      # 7. Deploy Kubernetes manifests
      - name: Deploy to Kind cluster
        run: |
          kubectl apply -f k8s/

      - name: Restart Nginx
        run: |
          kubectl rollout restart deployment nginx-service

      # 8. Verify Pods
      - name: Check Pods status
        run: kubectl get pods -A

      # 9. Optional: Run tests against services
      - name: Test Services
        run: |
          kubectl get svc
